const MEDIA = {
  
  movies: [

  ],

  indianmovies: [

  ],

  animated: [

  ],
  
  shows: [
    "a-knight-of-the-seven-kingdoms.png",
    "band-of-brothers.jpeg",
    "better-call-saul.jpeg",
    "bloodhounds.png",
    "bones.png",
    "breaking-bad.png",
    "brooklyn-nine-nine.png",
    "chernobyl.jpeg",
    "countdown.png",
    "daredevil.png",
    "dark.jpeg",
    "dexter.png",
    "doctor-who.jpg",
    "from.png",
    "game-of-thrones.png",
    "gotham.jpeg",
    "hannibal.jpeg",
    "house-of-cards.png",
    "house-of-the-dragon.png",
    "jack-ryan.png",
    "jessica-jones.jpeg",
    "karma.png",
    "loki.jpg",
    "lucifer.jpeg",
    "luther.jpeg",
    "mad-men.png",
    "mercy-for-none.png",
    "mindhunter.png",
    "mobland.jpg",
    "money-heist.png",
    "moon-knight.jpg",
    "mr-robot.png",
    "narcos.jpg",
    "peacemaker.png",
    "peaky-blinders.jpg",
    "prison-break.jpg",
    "reacher.jpg",
    "sex-education.png",
    "sherlock.png",
    "shogun.jpg",
    "snowfall.png",
    "spider-noir.png",
    "stranger-things.png",
    "succession.png",
    "suits.jpeg",
    "supernatural.jpg",
    "the-punisher.png",
    "the-big-bang-theory.jpg",
    "the-blacklist.jpeg",
    "the-boys.png",
    "the-continental.jpg",
    "the-defenders.jpeg",
    "the-flash.png",
    "the-good-doctor.png",
    "the-recruit.png",
    "the-rookie.png",
    "the-sopranos.jpeg",
    "the-vampire-diaries.jpg",
    "the-walking-dead.png",
    "the-wire.png",
    "the-witcher.jpg",
    "true-detective.png",
    "vikings.png",
    "wednesday.png",
    "you.png",
    "young-sheldon.png",
    "the-mentalist.png",
    ],

  indianshows: [
      
  ],

  anime: [
    "akame-ga-kill.png",
    "assassination-classroom.png",
    "attack-on-titan.png",
    "baki.png",
    "black-clover.png",
    "bleach.jpeg",
    "blue-lock.jpg",
    "bungo-stray-dogs.png",
    "chainsaw-man.png",
    "classroom-of-the-elite.jpg",
    "code-geass.jpeg",
    "death-note.jpg",
    "demon-slayer.png",
    "dragon-ball.png",
    "fairy-tail.png",
    "fate.png",
    "fire-force.png",
    "fullmetal-alchemist.png",
    "gintama.png",
    "haikyu.png",
    "hajime-no-ippo.png",
    "hells-paradise.png",
    "high-school-dxd.jpg",
    "hunter-x-hunter.png",
    "hyouka.jpg",
    "jojos-bizarre-adventure.png",
    "jujutsu-kaisen.png",
    "mashle.png",
    "mob-psycho-100.jpg",
    "my-hero-academia.png",
    "naruto.png",
    "noblesse.png",
    "one-punch-man.jpeg",
    "overlord.png",
    "ragna-crimson.png",
    "re-zero.jpg",
    "rent-a-girlfriend.jpg",
    "sakamoto-days.png",
    "solo-leveling.png",
    "spy-x-family.png",
    "the-daily-life-of-the-immortal-king.png",
    "the-eminence-in-shadow.png",
    "the-misfit-of-demon-king-academy.jpg",
    "the-quintessential-quintuplets.png",
    "the-seven-deadly-sins.png",
    "tokyo-revengers.png",
    "trapped-in-a-dating-sim.png",
    "vinland-saga.png",
    "wind-breaker.jpg",
    "dr-stone.png",
    "mushoku-tensei.png",
    "one-piece.jpg",
    "plunderer.png",
    "no-longer-allowed-in-another-world.jpg",
    "failure-frame.jpg",
    "blue-exorcist.png",
    "chained-soldier.png",
    "another.png",
    "berserk.png",
    "frieren.jpg",
    "hellsing.png",
    "k-on.jpeg",
    "kaguya-sama-love-is-war.png",
    "monster.png",
    "noragami.png",
    "psycho-pass.jpeg",
    "record-of-ragnarok.png",
    "steins-gate.jpg",
    "sword-art-online.jpeg",
    "the-rising-of-the-shield-hero.jpg",
    "tomodachi-game.png",
    "zom-100.png",
    "kaiju-no-8.png",
    "lord-of-mysteries.jpg",
    "reign-of-the-seven-spellblades.png",
    "the-irregular-at-magic-high-school.jpg",
    "wistoria-wand-and-sword.png",
    "witch-hat-atelier.png",

  ],

  animemovies: [

  ],

  manhwa: [

  ],
};