const MEDIA = {
  anime: [
    "akame-ga-kill.png",
    "assassination-classroom.png",
    "attack-on-titan.png",
    "baki.png",
    "black-clover.png",
    "bleach.jpeg",
    "blue-lock.jpg",
    "bungo-stray-dogs.png",
    "chainsaw-man.png",
    "classroom-of-the-elite.jpg",
    "code-geass.jpeg",
    "death-note.jpg",
    "demon-slayer.png",
    "dragon-ball.png",
    "fairy-tail.png",
    "fate.png",
    "fire-force.png",
    "fullmetal-alchemist.png",
    "gintama.png",
    "haikyu.png",
    "hajime-no-ippo.png",
    "hells-paradise.png",
    "high-school-dxd.jpg",
    "hunter-x-hunter.png",
    "hyouka.jpg",
    "jojos-bizarre-adventure.png",
    "jujutsu-kaisen.png",
    "mashle.png",
    "mob-psycho-100.jpg",
    "my-hero-academia.png",
    "naruto.png",
    "noblesse.png",
    "one-punch-man.jpeg",
    "overlord.png",
    "ragna-crimson.png",
    "re-zero.jpg",
    "rent-a-girlfriend.jpg",
    "sakamoto-days.png",
    "solo-leveling.png",
    "spy-x-family.png",
    "the-daily-life-of-the-immortal-king.png",
    "the-eminence-in-shadow.png",
    "the-misfit-of-demon-king-academy.jpg",
    "the-quintessential-quintuplets.png",
    "the-seven-deadly-sins.png",
    "tokyo-revengers.png",
    "trapped-in-a-dating-sim.png",
    "vinland-saga.png",
    "wind-breaker.jpg"
  ],

  movies: [],
  shows: [],
  animated: []
};